<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Group]" Member="Group">
    <Type Name="Group">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="vk" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="inst" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Concerts" Member="Concert">
    <Type Name="Concert">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="time" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="place" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="event" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="month" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>